# Yang Yang 2019
# This script is for generating sv file in shatterseek-read/signature-read input format
# 
# input files are:
# 1.independent-specimens.wgs.primary-plus.tsv
# this file is used to choose independent specimens
# 2. pbta-sv-manta.tsv
# this file is the original sv file generated by manta call
# 
# output files are:
# sv files for each specimens
# 
# output file format:
# chrom1, pos1, chrom2, pos2, SVtype, strand1, strand2, alt1, alt2, homolen, inserlen
# chrom and pos are breakpoint location
# SVtype is structral variation type, they are DUP, DEL, INV and TRA 
# strand1 and strand2 will be used in shatterseek analysis
# alt1 and alt2 were used to infer strand， you can ignore them
# homolen and inserlen will be used in signature analysis

library(stringr) 
library(rprojroot)
library(readr)

# Detect the ".git" folder -- this will in the project root directory.
# Use this as the root directory to ensure proper sourcing of functions no
# matter where this is called from
root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))

## =====================  Create A Subdirectory to Hold All The Output Files ===================== 
output_directory <- file.path(root_dir, "scratch/sv-vcf")
if (!dir.exists(output_directory)) {
  dir.create(output_directory, recursive = TRUE)
}

## ===================== Load  Independent Specimen List =====================
independent_specimen_list <-  read.table(file.path(root_dir, "data/independent-specimens.wgs.primary-plus.tsv"), header = TRUE, sep = "\t")

# bioid including all sample's names will be used later
bioid <- unique(independent_specimen_list$Kids_First_Biospecimen_ID)


## ===================== Load SV File =====================
sv_file <- read_tsv("data/pbta-sv-manta.tsv.gz")
# choose independent specimens
sv_analysis <-  sv_file[sv_file$Kids.First.Biospecimen.ID.Tumor %in% bioid,]


## ===================== Generate SV File In A Shatterseek-read Format =====================
for (i in bioid) {
  sv_individual = sv_analysis[sv_analysis$Kids.First.Biospecimen.ID.Tumor  == i,]
  ## TYPE == BND
  bnds <- sv_individual[sv_individual$SV.type == "BND", ]
  reads_id_bnd <- substr(bnds$ID, start = 1, stop = nchar(as.character(bnds$ID))-2)
  bnds_file <- matrix(NA, nrow = length(unique(reads_id_bnd)), ncol = 11)
  colnames(bnds_file) <- c("chrom1","pos1","chrom2","pos2","SVtype","strand1","strand2","alt1","alt2","homolen","inserlen")
  rownames(bnds_file) <- unique(reads_id_bnd)
  if (nrow(bnds)  != 0) {
    for (j in 1:nrow(bnds)) {
      id_name <- substr(bnds[j, 7], start = 1, stop = nchar(as.character(bnds[j, 7])) - 2)
      number  <-  as.character(as.numeric(substr(bnds[j, 7], start = nchar(as.character(bnds[j, 7])), stop = nchar(as.character(bnds[j, 7])))) + 1)
      bnds_file[id_name, paste("chrom", number, sep = "")] <- as.character(bnds$SV.chrom[j])
      bnds_file[id_name, paste("pos", number, sep = "")] <- as.character(bnds$SV.start[j])
      bnds_file[id_name, paste("alt", number, sep = "")] <- as.character(bnds$ALT[j])
      bnds_file[id_name, "SVtype"] <- "TRA"
      if (str_detect(as.character(bnds$INFO[j]),"HOMLEN=")) {
        bnds_file[id_name, "homolen"] <- gsub((".*HOMLEN="),"",as.character(bnds$INFO[j]))
        bnds_file[id_name, "homolen"] <- gsub((";.*"),"",bnds_file[id_name, "homolen"])
      } else {
        bnds_file[id_name, "homolen"] <- 0
      }
      if (str_detect(as.character(bnds$INFO[j]),"SVINSLEN=")) {
        bnds_file[id_name, "inserlen"] <- gsub((".*SVINSLEN="),"",as.character(bnds$INFO[j]))
        bnds_file[id_name, "inserlen"] <- gsub((";.*"),"",bnds_file[id_name, "inserlen"])
      } else {
        bnds_file[id_name, "inserlen"] <- 0
      }
      if (substr(bnds_file[id_name, paste("alt", number, sep = "")], start = 1, stop = 1) %in% c("A", "T", "C", "G")) {
        bnds_file[id_name, paste("strand", number, sep = "")] = "+"
      } else {
        bnds_file[id_name, paste("strand", number, sep = "")] = "-"
      }
    }
  }
  ## TYPE == DUP
  dups <- sv_individual[sv_individual$SV.type == "DUP", ]
  reads_id_dup <- substr(dups$ID, start = 1, stop = nchar(as.character(dups$ID)))
  dups_file <- matrix(NA, nrow = length(unique(reads_id_dup)), ncol = 11)
  colnames(dups_file) <- c("chrom1","pos1","chrom2","pos2","SVtype","strand1","strand2","alt1","alt2","homolen","inserlen")
  rownames(dups_file) <- unique(reads_id_dup)
  if (nrow(dups)  != 0) {
    for (j in 1:nrow(dups)) { 
      id_name <- substr(dups[j, 7], start = 1, stop = nchar(as.character(dups[j, 7])))
      dups_file[id_name, "chrom1"] <- as.character(dups$SV.chrom[j])
      dups_file[id_name, "chrom2"] <- as.character(dups$SV.chrom[j])
      dups_file[id_name, "pos1"] <- as.character(dups$SV.start[j])
      dups_file[id_name, "pos2"] <- as.character(dups$SV.end[j])
      dups_file[id_name, "SVtype"] <- "DUP"
      dups_file[id_name, "alt1"] <- as.character(dups$AnnotSV.ID[j])
      if (str_detect(as.character(dups$INFO[j]),"HOMLEN=")) {
        dups_file[id_name, "homolen"] <- gsub((".*HOMLEN="),"",as.character(dups$INFO[j]))
        dups_file[id_name, "homolen"] <- gsub((";.*"),"",dups_file[id_name, "homolen"])
      } else {
        dups_file[id_name, "homolen"] <- 0
      }
      if (str_detect(as.character(dups$INFO[j]),"SVINSLEN=")) {
        dups_file[id_name, "inserlen"] <- gsub((".*SVINSLEN="),"",as.character(dups$INFO[j]))
        dups_file[id_name, "inserlen"] <- gsub((";.*"),"",dups_file[id_name, "inserlen"])
      } else {
        dups_file[id_name, "inserlen"] <- 0
      }
      dups_file[id_name, "strand1"] = "-"
      dups_file[id_name, "strand2"] = "+"
    }
  }
  ## TYPE == DEL
  dels <- sv_individual[sv_individual$SV.type == "DEL", ]
  reads_id_del <- substr(dels$ID, start = 1, stop = nchar(as.character(dels$ID)))
  dels_file <- matrix(NA, nrow = length(unique(reads_id_del)), ncol = 11)
  colnames(dels_file) <- c("chrom1","pos1","chrom2","pos2","SVtype","strand1","strand2","alt1","alt2","homolen","inserlen")
  rownames(dels_file) <- unique(reads_id_del)
  if (nrow(dels)  != 0) {
    for (j in 1:nrow(dels)) { 
      id_name <- substr(dels[j, 7], start = 1, stop = nchar(as.character(dels[j, 7])))
      dels_file[id_name, "chrom1"] <- as.character(dels$SV.chrom[j])
      dels_file[id_name, "chrom2"] <- as.character(dels$SV.chrom[j])
      dels_file[id_name, "pos1"] <- as.character(dels$SV.start[j])
      dels_file[id_name, "pos2"] <- as.character(dels$SV.end[j])
      dels_file[id_name, "SVtype"] <- "DEL"
      dels_file[id_name, "alt1"] <- as.character(dels$AnnotSV.ID[j])
      if (str_detect(as.character(dels$INFO[j]),"HOMLEN=")) {
        dels_file[id_name, "homolen"] <- gsub((".*HOMLEN="),"",as.character(dels$INFO[j]))
        dels_file[id_name, "homolen"] <- gsub((";.*"),"",dels_file[id_name, "homolen"])
      } else {
        dels_file[id_name, "homolen"] <- 0
      }
      if (str_detect(as.character(dels$INFO[j]),"SVINSLEN=")) {
        dels_file[id_name, "inserlen"] <- gsub((".*SVINSLEN="),"",as.character(dels$INFO[j]))
        dels_file[id_name, "inserlen"] <- gsub((";.*"),"",dels_file[id_name, "inserlen"])
      } else {
        dels_file[id_name, "inserlen"] <- 0
      }
      dels_file[id_name, "strand1"] = "+"
      dels_file[id_name, "strand2"] = "-"
    }
  }
  ## TYPE == INV
  invs <- sv_individual[sv_individual$SV.type == "INV", ]
  reads_id_inv <- substr(invs$ID, start = 1, stop = nchar(as.character(invs$ID)))
  invs_file <- matrix(NA, nrow = length(unique(reads_id_inv)), ncol = 11)
  colnames(invs_file) <- c("chrom1","pos1","chrom2","pos2","SVtype","strand1","strand2","alt1","alt2","homolen","inserlen")
  rownames(invs_file) <- unique(reads_id_inv)
  if (nrow(invs)  != 0) {
    for (j in 1:nrow(invs)) { 
      id_name <- substr(invs[j, 7], start = 1, stop = nchar(as.character(invs[j, 7])))
      invs_file[id_name, "chrom1"] <- as.character(invs$SV.chrom[j])
      invs_file[id_name, "chrom2"] <- as.character(invs$SV.chrom[j])
      invs_file[id_name, "pos1"] <- as.character(invs$SV.start[j])
      invs_file[id_name, "pos2"] <- as.character(invs$SV.end[j])
      invs_file[id_name, "SVtype"] <- "INV"
      invs_file[id_name, "alt1"] <- as.character(invs$AnnotSV.ID[j])
      if (str_detect(as.character(invs$INFO[j]),"HOMLEN=")) {
        invs_file[id_name, "homolen"] <- gsub((".*HOMLEN="),"",as.character(invs$INFO[j]))
        invs_file[id_name, "homolen"] <- gsub((";.*"),"",invs_file[id_name, "homolen"])
      } else {
        invs_file[id_name, "homolen"] <- 0
      }
      if (str_detect(as.character(invs$INFO[j]),"SVINSLEN=")) {
        invs_file[id_name, "inserlen"] <- gsub((".*SVINSLEN="),"",as.character(invs$INFO[j]))
        invs_file[id_name, "inserlen"] <- gsub((";.*"),"",invs_file[id_name, "inserlen"])
      } else {
        invs_file[id_name, "inserlen"] <- 0
      }
      if (str_detect(invs$INFO[j],"INV5")) {
        invs_file[id_name, "strand1"] = "+"
        invs_file[id_name, "strand2"] = "+"
        invs_file[id_name, "SVtype"] <- "h2hINV"
      } else {
        invs_file[id_name, "strand1"] = "-"
        invs_file[id_name, "strand2"] = "-"
        invs_file[id_name, "SVtype"] <- "t2tINV"
      }
    }
  }
  
  ## Merge four types SV
  sv_merge <- rbind(dups_file, dels_file, invs_file, bnds_file)
  sv_merge <- sv_merge[is.na(sv_merge[, 1]) == FALSE & is.na(sv_merge[, 3]) == FALSE, ]
  outputname_sv_merge <- paste(i,".vcf",sep = "")
  outputname_sv_merge  <- file.path(output_directory,outputname_sv_merge)
  
  ## Shatterseek only accept file with chrom1-22,X, so remove chrY and ChrM
  sv_merge_withoutY_withoutM <- sv_merge[sv_merge[,1] != "Y" & sv_merge[,3] != "Y" & sv_merge[,1] != "M" & sv_merge[,3] != "M",]
  outputname_sv_merge_withoutY_withoutM <- paste(i,"_withoutYandM.vcf",sep = "")
  outputname_sv_merge_withoutY_withoutM <- file.path(output_directory,outputname_sv_merge_withoutY_withoutM)
  
  ## output files
  write.table(sv_merge,file = outputname_sv_merge,sep = "\t",quote = FALSE,row.names = TRUE,col.names = NA)
  write.table(sv_merge_withoutY_withoutM,file = outputname_sv_merge_withoutY_withoutM,sep = "\t",quote = FALSE,row.names = TRUE,col.names = NA)
}


