#!/bin/bash
set -eo pipefail

# set the analyses folder as workdir variable
WORKDIR='analyses/tcga-capture-kit-investigation'


# retrieve the TCGA's exome capture kit from GDC's file API endpoint
# this will generate tcga-capture_kit-info.tsv file under the result folder
python3 $WORKDIR/scripts/get-tcga-capture_kit.py


# download all BED from tcga-capture_kit-info.tsv and add chr prefix
sed 1d $WORKDIR/results/tcga-capture_kit-info.tsv \
| cut -f3 | tr "\|" "\n" | sort -u \
| while read i
do 
    filename=`basename $i`
    curl -s $i | awk '{print "chr"$0}' > scratch/$filename
done


## get intersection between all the BED files
bedtools intersect -a data/WGS.hg38.strelka2.unpadded.bed -b data/WGS.hg38.mutect2.vardict.unpadded.bed \
| bedtools intersect -a - -b data/WGS.hg38.lancet.unpadded.bed \
| bedtools intersect -a - -b $WORKDIR/results/hg38lft-whole_exome_agilent_1.1_refseq_plus_3_boosters.targetIntervals.bed \
| bedtools intersect -a - -b $WORKDIR/results/hg38lft-whole_exome_agilent_designed_120.targetIntervals.bed \
| bedtools intersect -a - -b $WORKDIR/results/hg38lft-whole_exome_agilent_plus_tcga_6k.targetIntervals.bed \
| bedtools intersect -a - -b $WORKDIR/results/hg38lft-tcga_6k_genes.targetIntervals.bed \
> scratch/intersect-all-tcga_pbta.bed


## get all the PBTA and TCGA maf into BED-like format and intersect with 
## the region generated by the above step
for caller in 'lancet' 'mutect2' 'strelka2'
do
    zcat < data/pbta-snv-$caller.vep.maf.gz \
    | sed 1,2d | cut -f5-7,16 \
    | bedtools intersect -a - -b scratch/intersect-all-tcga_pbta.bed \
    | cut -f4 | sort | uniq -c \
    | awk -v c=$caller 'BEGIN{OFS="\t"}{print $2,$1,"PBTA",c}';
    zcat < data/pbta-tcga-snv-$caller.vep.maf.gz \
    | sed 1,2d | cut -f5-7,16 \
    | bedtools intersect -a - -b scratch/intersect-all-tcga_pbta.bed \
    | cut -f4 | sort | uniq -c \
    | awk -v c=$caller 'BEGIN{OFS="\t"}{print $2,$1,"TCGA",c}';
done > scratch/somatic-count.tsv


## matching histology for the mutation counts file generated by the step above
touch scratch/tumor_type.tsv
sed 1d data/pbta-histologies.tsv | cut -f1,17 > scratch/tumor_type.tsv && \
sed 1d data/pbta-tcga-manifest.tsv | cut -f2,5 >> scratch/tumor_type.tsv
cat scratch/somatic-count.tsv | cut -f1 \
| while read i
do
    grep $i scratch/tumor_type.tsv | cut -f2
done | paste scratch/somatic-count.tsv - > scratch/somatic-count_with-histologies.tsv


## boxplot from ggplot and saved to plots folder
Rscript $WORKDIR/scripts/boxplot.R scratch/somatic-count_with-histologies.tsv $WORKDIR/plots

