---
title: "Segment to gene mapping in ATRT"
output: html_notebook
author: J. Taroni for ALSF CCDL
date: 2019
---

From [this comment](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/182#discussion_r340587968) on #182:

> may advise starting with ATRT's and SMARCB1 deletions

Here, I'm looking at the output of `01-prepare-cn-file.R` to see if we recover that information in the segment to gene mapping.
The CNVkit SEG file was used for `results/annotated_cn.tsv`.

```{r}
`%>%` <- dplyr::`%>%`
```

### Read in data

```{r}
# read in the output of `01-prepare-cn-file.R`
annotation_cn <- readr::read_tsv(file.path("results", "annotated_cn.tsv"))
# read in the clinical file that has the disease type information
histologies_df <- readr::read_tsv(file.path("..", "..", "data", 
                                            "pbta-histologies.tsv"))
```

### Look at copy number information for ATRT

```{r}
# get ATRT biospecimen identifiers
atrt_specimens <- histologies_df %>%
  dplyr::filter(disease_type_new == "Atypical Teratoid Rhabdoid Tumor") %>%
  dplyr::pull(Kids_First_Biospecimen_ID)
```

```{r}
# filter the gene-level CN information to ATRT samples and gene symbols
# containing 'SMARC'
annotation_cn %>%
  dplyr::filter(biospecimen_id %in% atrt_specimens,
                grepl("SMARCB1", gene_symbol))
```

