---
title: "Comparison of Expected and Observed MB Classification"
output:
  html_document:
    df_print: paged
params:
  expected_input:
    value: input/expected_class.rds
  observed_input:
    value: results/mb-classified.rds
---
  
```{r include = FALSE}
knitr::opts_chunk$set(comment = NA)
getOption(x = 'DT.warn.size', default = FALSE)
```

```{r load_packages, echo = FALSE}
# load libraries
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(knitr))
suppressPackageStartupMessages(library(DT))
```

```{r read_data, echo = FALSE}
# read input
obs.class <- readRDS(params$observed_input)
exp.class <- readRDS(params$expected_input)
exp.class <- exp.class %>%
  mutate(pathology_subtype = replace(pathology_subtype, pathology_subtype == "Group 3 or 4", "Group3, Group4")) %>%
  mutate(pathology_subtype = gsub(" ", "", pathology_subtype))
```

```{r dt_function, echo = FALSE}
# custom datatable function
viewDataTable <- function(dat){
  DT::datatable(dat,
                rownames = FALSE,
                filter = "bottom",
                class = 'cell-border stripe',
                options = list(pageLength = 5,
                               searchHighlight = TRUE,
                               scrollX = TRUE,
                               dom = 'tpi',
                               initComplete = JS("function(settings, json) {",
                                                 "$(this.api().table().header()).css({'background-color':
                                            '#004467', 'color': '#fff'});","}"))
  )
}
```

## {.tabset .tabset-fade}

### MM2S Classifier

```{r, echo = FALSE, warning = FALSE, message = FALSE}
mm2s.corrected <- obs.class[[1]]
mm2s.corrected <- exp.class %>%
  inner_join(mm2s.corrected, by = c('Kids_First_Biospecimen_ID' = 'sample')) %>%
  mutate(match = str_detect(pathology_subtype, best.fit))

# accuracy
mm2s.corrected.acc <- mm2s.corrected %>%
  filter(!is.na(pathology_subtype)) %>%
  group_by(match) %>%
  summarise(n = n()) %>%
  mutate(Accuracy = paste0(n/sum(n)*100, '%')) %>%
  filter(match) %>%
  .$Accuracy
```

#### Corrected matrix (Accuracy `r mm2s.corrected.acc`)

```{r echo = FALSE}
viewDataTable(mm2s.corrected)
```


```{r, echo = FALSE, warning = FALSE, message = FALSE}
mm2s.uncorrected <- obs.class[[2]]
mm2s.uncorrected <- exp.class %>%
  inner_join(mm2s.uncorrected, by = c('Kids_First_Biospecimen_ID' = 'sample')) %>%
  mutate(match = str_detect(pathology_subtype, best.fit))

# accuracy
mm2s.uncorrected.acc <- mm2s.uncorrected %>%
  filter(!is.na(pathology_subtype)) %>%
  group_by(match) %>%
  summarise(n = n()) %>%
  mutate(Accuracy = paste0(n/sum(n)*100, '%')) %>%
  filter(match) %>%
  .$Accuracy
```

#### Uncorrected matrix (Accuracy `r mm2s.uncorrected.acc`)

```{r echo = FALSE}
viewDataTable(mm2s.uncorrected)
```

### medulloPackage 

```{r, echo = FALSE, warning = FALSE, message = FALSE}
medullo.classifier.corrected <- obs.class[[3]]
medullo.classifier.corrected <- exp.class %>%
  inner_join(medullo.classifier.corrected, by = c('Kids_First_Biospecimen_ID' = 'sample')) %>%
  mutate(match = str_detect(pathology_subtype, best.fit))

# accuracy
medullo.classifier.corrected.acc <- medullo.classifier.corrected %>%
  filter(!is.na(pathology_subtype)) %>%
  group_by(match) %>%
  summarise(n = n()) %>%
  mutate(Accuracy = paste0(n/sum(n)*100, '%')) %>%
  filter(match) %>%
  .$Accuracy
```

#### Corrected matrix (Accuracy `r medullo.classifier.corrected.acc`)

```{r echo = FALSE}
viewDataTable(medullo.classifier.corrected)
```

```{r, echo = FALSE, warning = FALSE, message = FALSE}
medullo.classifier.uncorrected <- obs.class[[4]]
medullo.classifier.uncorrected <- exp.class %>%
  inner_join(medullo.classifier.uncorrected, by = c('Kids_First_Biospecimen_ID' = 'sample')) %>%
  mutate(match = str_detect(pathology_subtype, best.fit))

# accuracy
medullo.classifier.uncorrected.acc <- medullo.classifier.uncorrected %>%
  filter(!is.na(pathology_subtype)) %>%
  group_by(match) %>%
  summarise(n = n()) %>%
  mutate(Accuracy = paste0(n/sum(n)*100, '%')) %>%
  filter(match) %>%
  .$Accuracy
```

#### Uncorrected matrix (Accuracy `r medullo.classifier.uncorrected.acc`)

```{r echo = FALSE}
viewDataTable(medullo.classifier.uncorrected)
```
