---
title: "Create subset files for CI"
output: 
  html_notebook:
    toc: TRUE
    toc_float: TRUE
author: C. Savonen for ALSF CCDL
date: 2019
---


#### Usage

To run this from the command line, use:
```
Rscript -e "rmarkdown::render('analyses/tmb-calculations/01-set-up-tcga.Rmd', 
                              clean = TRUE)"
```
,
_This assumes you are in the top directory of the repository._

## Setup

#### Packages and functions

```{r}
# R.utils is required to gzip files here
if (!("maftools" %in% installed.packages())) {
  install.packages("R.utils")
}
```

`magrittr` pipe.

```{r}
`%>%` <- dplyr::`%>%`
```

Custom function for writing gzipped MAF files.

```{bash}
wget https://gdc.cancer.gov/system/files/authenticated%20user/0/dtt-ui_v0.5.4_Ubuntu_x64.zip

unzip gdc-client_v1.0.1_Ubuntu14.04_x64.zip ./gdc-client

cp -pi ./gdc-client /usr/local/bin (if this does not work)
sudo cp -pi ./gdc-client /usr/local/bin

gdc-client download -m tcga_data/gdc_manifest_maf_files.txt
```

## Session Info

```{r}
sessionInfo()
```
