---
title: "Generating summaries for README file"
output: 
  html_notebook:
    toc: true
    toc_float: true
author: Run Jin for D3b
date: 2022
---

The purpose of this notebook is to generate tables used for README file

```{r load library}
library(tidyverse)
```

## read in histology file 
```{r read in files}
data_dir <- "../../data"
histology <- read_tsv(file.path(data_dir,"pbta-histologies.tsv"), guess_max = 10000)
```

## generate tables/lists for README file
### clean up table
```{r}
histology_select <- histology %>%
  dplyr::select(harmonized_diagnosis, cancer_group) %>%
  dplyr::filter(!is.na(harmonized_diagnosis)) %>%
  distinct() %>%
  # get the cancer group from harmonized diagnosis (before additional change)
  dplyr::mutate(cancer_group_pre_mod = str_extract(harmonized_diagnosis, "[^,]*")) %>%
  
  # generate column `has_subtype_removed` to indicate whether cancer group equals 
  dplyr::mutate(has_subtype_removed = case_when(
    cancer_group_pre_mod == harmonized_diagnosis ~ "No",
    TRUE ~ "Yes"
  )) %>%
  
    # generate column `additional_modi` to indicate whether additional modifications were done
  dplyr::mutate(additional_modi = case_when(
    cancer_group_pre_mod == cancer_group ~ "No",
    TRUE ~ "Yes"
  ))

```

### cancer group without molecular subtypes
```{r}
histology_select %>%
  dplyr::filter(has_subtype_removed == "No") %>%
  dplyr::select(cancer_group_pre_mod) %>%
  distinct() %>%
  arrange(cancer_group_pre_mod) %>%
  knitr::kable()
```

### cancer group with molecular subtype
```{r}
histology_select %>%
  dplyr::filter(has_subtype_removed == "Yes") %>%
  dplyr::select(cancer_group_pre_mod) %>%
  distinct() %>%
  arrange(cancer_group_pre_mod) %>%
  knitr::kable()
```

### cancer group that undergo additional modifications with or without previous subtype removal
```{r}
histology_select %>%
  dplyr::filter(additional_modi == "Yes") %>%
  dplyr::select(cancer_group_pre_mod,
                cancer_group) %>%
  distinct() %>%
  dplyr::arrange(cancer_group_pre_mod) %>%
  knitr::kable()
```

## generate session info
```{r}
sessionInfo()
```

