---
title: "LGAT final table for BRAFV600E and BRAF fusion"
output: html_notebook
---

This script uses subsetted LGAT wgs file and fusion files from data release to identify samples with BRAF V600E mutations and BRAF fusion

```{r}
library("tidyverse")
```


### Read files
    
```{r}

# to get root directory
root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))
# get clinical file for participant and sample_id columns associated with bs_ids
clinical <- readr::read_tsv(file.path(root_dir,"data", "pbta-histologies.tsv")) %>%
  select("Kids_First_Biospecimen_ID","Kids_First_Participant_ID","sample_id","short_histology")
# get subsetted wgs file
subsetWgs<-readr::read_tsv(file.path(root_dir,"analyses","molecular-subtyping-LGAT","lgat-subset","LGAT_snv_subset.tsv")) %>% 
  dplyr::select("Tumor_Sample_Barcode","BRAF_V600E")
# get BRAF fusion list per sample
brafFusion<-readr::read_tsv(file.path(root_dir, "data","pbta-fusion-recurrently-fused-genes-bysample.tsv")) %>%
  dplyr::select(Sample,BRAF) %>%
  dplyr::filter(BRAF==1)
# get putative oncogene fusion list
kiaabrafFusion<-readr::read_tsv(file.path(root_dir, "data","pbta-fusion-putative-oncogenic.tsv")) %>%
  dplyr::select(Sample, FusionName) %>% unique() %>%
  dplyr::filter(grepl("KIAA1549--BRAF",FusionName))


```
    
### Merge clinical file with BRAF fusion and wgs data for BRAF V600E   
    
```{r}
# LGAT WGS subset with kids_first_participant and sample_id
subsetWgs<-subsetWgs %>% 
  dplyr::left_join(clinical,by=c("Tumor_Sample_Barcode"="Kids_First_Biospecimen_ID")) %>%
  dplyr::rename("Kids_First_Biospecimen_ID_DNA"="Tumor_Sample_Barcode")

# BRAF fusion with kids_first_participant and sample_id
brafFusion<-brafFusion %>% 
  dplyr::left_join(clinical,by=c("Sample"="Kids_First_Biospecimen_ID")) %>%
  dplyr::rename("Kids_First_Biospecimen_ID_RNA"="Sample")
  
#kiaabraf fusion with kids_first_participant and sample_id
kiaabrafFusion<-kiaabrafFusion %>% dplyr::left_join(clinical,by=c("Sample"="Kids_First_Biospecimen_ID")) %>%
  dplyr::rename("Kids_First_Biospecimen_ID_RNA"="Sample")

```
    
### merge all subset data for braf fusion and braf V600E mutations
    
```{r}

final_table<-clinical %>% 
  dplyr::select(-Kids_First_Biospecimen_ID) %>%
  # select LGAT
  dplyr::filter(short_histology == "LGAT") %>%
  # add metadata to kiaabraf dataset
  left_join(kiaabrafFusion,by=c("Kids_First_Participant_ID","sample_id","short_histology")) %>%
  # add metadat to braffusion dataset
  left_join(brafFusion,by=c("Kids_First_Participant_ID","sample_id","Kids_First_Biospecimen_ID_RNA","short_histology")) %>% 
  # add metadata to wgs dataset
  left_join(subsetWgs,by=c("Kids_First_Participant_ID","sample_id","short_histology")) %>%
  # add molecular_subtype column 
 dplyr::mutate(molecular_subtype=dplyr::case_when(
    # if RNAseq sample has BRAF fusion and WGS sample is not available or is present without BRAF V600E; a condition is.na(BRAF) is also used to capture instances where the sample was not selected in recurrent-fusion sample selection( for example progressive sample was not selected if a initial tumor RNAseq was found for that patient)
    FusionName=="KIAA1549--BRAF" & (BRAF==1|is.na(BRAF)) & (BRAF_V600E=="No"|is.na(BRAF_V600E)) ~"LGG, BRAF fusion",
    # if RNAseq sample doesn't have BRAF fusion and WGS sample has BRAF V600E
    is.na(FusionName) & is.na(BRAF) & BRAF_V600E=="Yes"~ "LGG, BRAF V600E",
    # if RNAseq sample doesn't have BRAF fusion and WGS sample doesn't have BRAF V600E
    is.na(FusionName) & is.na(BRAF) & BRAF_V600E=="No" ~ "LGG, BRAF wildtype",
    # if RNAseq sample has braf fusion and WGS has BRAF V600E mutation; a condition is.na(BRAF) is also used to capture instances where the sample was not selected in recurrent-fusion sample selection( for example progressive sample was not selected if a initial tumor RNAseq was found for that patient)
    FusionName=="KIAA1549--BRAF" & (BRAF==1|is.na(BRAF)) & BRAF_V600E=="Yes" ~"LGG, BRAF V600E/fusion",
    # if no fusion calls present in RNAseq and no WGS data is available
    is.na(FusionName) & is.na(BRAF) & is.na(BRAF_V600E) ~ "LGG,To be classified")) %>%
  dplyr::select("Kids_First_Participant_ID","sample_id","Kids_First_Biospecimen_ID_DNA","Kids_First_Biospecimen_ID_RNA","molecular_subtype")

                                                   
readr::write_tsv(final_table,file.path(root_dir,"analyses","molecular-subtyping-LGAT","results","lgat_subtyping.tsv"))


```
    
    
    
