---
title: "CNV GISTIC Plots"
output:   
  html_notebook: 
    toc: true
    toc_float: true
---

### Usage

This script is intended to be run via the command line from the top directory
of the repository as follows:

```
Rscript -e "rmarkdown::render('analyses/cnv-chrom-plot/gistic_plot.Rmd', 
                              clean = TRUE)"
```

### Set Up

```{r}
# This will be needed to create the frequency and proportion aberration plots 
if (!("maftools" %in% installed.packages())) {
  install.packages("BiocManager")
  BiocManager::install("maftools")
}
if (!("ggbio" %in% installed.packages())) {
  install.packages("BiocManager")
  BiocManager::install("ggbio")
}
library("ggbio")

# Magrittr pipe
`%>%` <- dplyr::`%>%`
```

### Directories and Files

```{r}
# Path to input directory
input_dir <- file.path("..", "..", "data")

# Path to gistic zip file results
gistic_zip <- file.path(input_dir, "pbta-cnv-cnvkit-gistic.zip")

# Zip to here
gistic_results <- file.path(input_dir, "gistic")

# Path to output directory
output_dir <- "plots"

# Create the output dir if it does not exist
if (!dir.exists(output_dir)) {
  dir.create(output_dir, recursive = TRUE)
}
```

Unzip and set up GISTIC results folder. 

```{r}
if (!dir.exists(gistic_results)){
  unzip(gistic_zip, exdir = gistic_results)
}
gistic_results <- file.path(gistic_results, "2019-12-10-gistic-results-cnvkit")
```

### Read in data 

```{r}
# Read in metadata
metadata <-
  readr::read_tsv(file.path(input_dir, "pbta-histologies.tsv"))
```
Read in the GISTIC scores file and format the data.

```{r}
gistic_scores <- readr::read_tsv(file.path(gistic_results, "scores.gistic")) %>% 
  dplyr::rename("gscore" = "G-score") %>% 
  # Recode 23 and 24 as X and Y. 
  dplyr::mutate(Chromosome = dplyr::recode(Chromosome,
                              X = "23",
                              Y = "24"), 
                # Turn `Del` scores into negative `G-scores` 
                # This is how GISTIC shows the scores. 
                gscore = dplyr::case_when(
                  Type == "Del" ~ -gscore,
                  TRUE ~ gscore
                  )
                )
```

### Make GISTIC data into GRanges object

```{r}
gistic_ranges <- GenomicRanges::GRanges(
  seqnames = gistic_scores$Chromosome,
  ranges = IRanges::IRanges(
    start = gistic_scores$Start,
    end = gistic_scores$End
  ),
  score = gistic_scores$gscore,
  mcols = gistic_scores
)
```

### Plot the GISTIC scores

```{r}
ggplot2::ggplot(gistic_ranges) + 
  geom_bar(ggplot2::aes(y = score, fill = mcols.Type), scales = "free") + 
  ggplot2::theme_classic() +
  ggplot2::theme(axis.text.x = ggplot2::element_text(size = 3, angle = 45, hjust = 1)) + 
  colorblindr::scale_fill_OkabeIto(name = "Type") + 
  ggplot2::ylab("G-scores") 

  
```

### Save the plot as PNG. 

```{r}
ggplot2::ggsave(filename = file.path(plots_dir, "gistic_plot.png"), 
                width = 10, 
                height = 3, 
                units = "in")
```

# Session Info

```{r}
sessionInfo()
```

