name: Build Docker

# Controls when the action will run. 
# Triggers the workflow for a pull request for
# dev when the Dockerfile file changes.
on:
  pull_request:
    branches: [ dev ]
    paths: [ Dockerfile ]

jobs:
  build_docker:
    runs-on: ubuntu-18.04
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
